# This workflow will do a clean install of node dependencies, build the source code and run tests across different versions of node
# For more information see: https://help.github.com/actions/language-and-framework-guides/using-nodejs-with-github-actions

name: Node.js CI


on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
    # checkout the repo
    - name: 'Checkout Github Action' 
      uses: actions/checkout@master
    
    - name: Setup Node 13.x
      uses: actions/setup-node@v1
      with:
        node-version: '13.x'
    - name: 'npm install, build, and test'
      run: | 
        npm ci
        npm test
      working-directory: ./apis/userprofile
       
    - name: 'Run Azure webapp deploy action using publish profile credentials'
      uses: azure/webapps-deploy@v2
      with: 
        app-name: openhackcy50wpt9userprofile-staging
        slot-name:  production
        publish-profile: ${{ secrets.azureWebAppPublishProfile }}
        